from pydantic_settings import BaseSettings, SettingsConfigDict
from pathlib import Path

[theme]


base="dark"


primaryColor="#00A99D"
backgroundColor="#111111"
secondaryBackgroundColor="#1E1E1E"
textColor="#EAEAEA"
font="sans serif"

